apiVersion: v1
kind: Service
metadata:
  name: route-alarm-app-service
spec:
  selector:
    app: route-alarm-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000